[package]
name = "tracing-defmt"
version = "0.1.0"
edition = "2024"

[dependencies]
defmt = "0.3"
tracing-defmt-macros = { path = "macros" }

[dev-dependencies]
defmt = "0.3"

[workspace]
members = ["macros"]
